name = "ai-floorplans"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[containers]]
class_name = "FloorplanSessionDO"
image = "../container/Dockerfile"

[[durable_objects.bindings]]
name = "FLOORPLAN_SESSION_DO"
class_name = "FloorplanSessionDO"

# Workers AI binding for natural language processing
[ai]
binding = "AI"











# Queue for asynchronous task processing
[[queues.producers]]
binding = "PLANNER_TASKS"
queue = "planner-tasks-queue"

[[queues.consumers]]
queue = "planner-tasks-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3

# R2 bucket for storing plan files (optional)
[[r2_buckets]]
binding = "PLANNER_STORAGE"
bucket_name = "react-planner-storage"

# KV for metadata and caching (optional)                                    
[[kv_namespaces]]                                                           
binding = "PLANNER_METADATA"                                                
id = "02bba12a2c5e457999fa0ed3016f1f37" 
# Environment variables
[vars]
ENVIRONMENT = "production"
LOG_LEVEL = "info"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true



[[migrations]]
tag = "v10-final-cleanup"
new_sqlite_classes = ["FloorplanSessionDO"]
